before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Wvg2eigCv+4QEafrD83cSPZeNTeX+8e+2Ab7QAv+0SuGcJkuzKq6eyXcLQ0/4qB8mAsWJ0I79J8bhtLxd2GMfcuMe3KQFukofLid94M9DXn/2unkozu14c16ZfCPYTn7B+qODA7f365tLL+ouLos/qYwdsgoeR0Y4WiS7dkmH6F+7aProLHDEsDhXNdViGUJuuLYHIsnuQ57EEehy2mf9wSI5UMiT1zgH3onbxIqJ4c2UwJNAy5zvnyFAkPsx5waDZMFZg9AlR//xmgGOceyK4SX/u+uEvNRcgVXMIzPL1O/HvahAgciYx3XpQSM9hWwWPycWywA1TRTj5/ItKDnWhdHaRKjwVAQep6IHG5mYPeWI4wqzprpin2dmrVjLD2RHcLSrhHzvfnt68sQTjA6RaLKeUte5B/EUdEmx4pJzoQoDc6XMwiui0GWZ6j+lRzxBYFtW2pj3DetKOCcbfkQY27c2mSf/Ixqcc9/0Ln1KikwHTxU088gQ8Nc0xgWPHkUMIYzAyufvIh6n7HtNFaruIeM6cyWvQi8zrdakG7ylTUqZKohakS3y0+vosbo7cHF3520BI1Fd/x29HiuFS/rLyhtxYE7gqSW8M1BImC+38QQgI1FISbVWMQTJSj5j93bpUYOttEOHVmYZ7DIN9bp9Z+NpmkB7L6PVD/VyiYBTHM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
